WHMSWebApp2/Models/PartnerViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using WHMSData.Models;

namespace WHMSWebApp2.Models
{
    public class PartnerViewModel
    {
        [Range(1, int.MaxValue, ErrorMessage = "ID should be a positive number")]
        public int Id { get; set; }

        [MinLength(4, ErrorMessage = "Partner Name is required!")]
        [MaxLength(30)]
        public string Name { get; set; }

        [Required(ErrorMessage = "Address is required!")]
        public string Address { get; set; }

        [Required(ErrorMessage = "City is required!")]
        public string City { get; set; }

        [StringLength(11)]
        [MinLength(11,ErrorMessage="Please enter a valid VAT number (ex: BG123456789)")]
        public string VAT { get; set; }

        public string CreatorId { get; set; }

        public string Creator { get; set; }

        public DateTime CreatedOn { get; set; }

        public DateTime ModifiedOn { get; set; }

        public bool CanUserEdit { get; set; }

        public bool CanUserDelete { get; set; }

        public PartnerViewModel SearchResult { get; set; }

        public ICollection<PartnerViewModel> SearchResults { get; set; }

        public IOrderedEnumerable<SelectListItem> Cities { get; set; }

        public bool ConfirmationToDelete { get; set; }

        public IOrderedEnumerable<SelectListItem> Addresses { get; set; }

        public List<Address> AddressesList { get; set; }

        public int AddressId { get; set; }

        public ICollection<Order> Orders { get; set; }

    }
}

WHMSWebApp2/Controllers/PartnerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Caching.Memory;
using System;
using System.Linq;
using System.Threading.Tasks;
using WHMS.Services.Contracts;
using WHMSData.Models;
using WHMSWebApp2.Extensions;
using WHMSWebApp2.Mappers;
using WHMSWebApp2.Models;

namespace WHMSWebApp2.Controllers
{
    public class PartnerController : Controller
    {
        private IMemoryCache cache;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IPartnerService partnerService;
        private IAddressService addressService;
        private readonly ITownService townService;
        private readonly IViewModelMapper<Partner, PartnerViewModel> partnerMapper;
        private readonly IOrderService orderService;

        public PartnerController(IMemoryCache cache, UserManager<ApplicationUser> userManager, IPartnerService partnerService, IAddressService addressService, ITownService townService, IViewModelMapper<Partner, PartnerViewModel> partnerMapper, IOrderService orderService)
        {
            this.cache = cache ?? throw new ArgumentNullException(nameof(cache));
            this.userManager = userManager ?? throw new ArgumentNullException(nameof(userManager));
            this.partnerService = partnerService ?? throw new ArgumentNullException(nameof(partnerService));
            this.addressService = addressService ?? throw new ArgumentNullException(nameof(addressService));
            this.townService = townService ?? throw new ArgumentNullException(nameof(townService));
            this.partnerMapper = partnerMapper ?? throw new ArgumentNullException(nameof(partnerMapper));
            this.orderService = orderService ?? throw new ArgumentNullException(nameof(orderService));
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Create()
        {
            PartnerViewModel model = new PartnerViewModel()
            {
                AddressesList = await this.addressService.GetAllAddressesAsync(),
                Cities = new SelectList(await this.townService.GetAllTownsAsync(), "Id", "Name").OrderBy(x => x.Text)
            };

            return View(model);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PartnerViewModel model)
        {
            cache.Remove(userManager.GetUserName(User));

            ModelState.Remove("Id");
            ModelState.Remove("Address");
            ModelState.Remove("City");
            if ((await this.partnerService.GetAllPartners()).Any(p => p.Name == model.Name))
            {
                ModelState.AddModelError("Name", "Name is already used");
            }
            if (model.AddressId == 0 && model.City == null ||
                model.AddressId == 0 && model.City == "Please choose a city")
            {
                ModelState.AddModelError("City", "City is required");
            }
            if (model.AddressId == 0 && model.Address == null)
            {
                ModelState.AddModelError("Address", "Address is required");
            }
            if (model.AddressId == 0)
            {
                ModelState.Remove("AddressId");
            }
            model.Cities = new SelectList(await this.townService.GetAllTownsAsync(), "Id", "Name").OrderBy(x => x.Text);
            model.AddressesList = await this.addressService.GetAllAddressesAsync();

            if (ModelState.IsValid)
            {
                Town town;
                Address address;
                if (model.AddressId == 0)
                {
                    town = await this.townService.GetTownAsync(model.City);

                    if (town == null || town.IsDeleted)
                    {
                        town = await this.townService.AddAsync(model.City);
                    }

                    address = await this.addressService.AddAsync(town, model.Address);
                }
                else
                {
                    address = await this.addressService.GetAddressByIdAsync(model.AddressId);
                }

                ApplicationUser user = await this.userManager.GetUserAsync(User);
                var newPartner = await this.partnerService
                    .AddAsync(model.Name, user, address, model.VAT);

                return RedirectToAction(nameof(Details), new { id = newPartner.Id });
            }
            else
            {
                return View(model);
            }
        }

        [Authorize]
        public async Task<IActionResult> Details(int id)
        {
            var partner = await this.partnerService.GetByIdAsync(id);

            var model = partnerMapper.MapFrom(partner);
           
            model.CanUserEdit = model.CreatorId == this.User.GetId() || this.User.IsInRole("Admin") || this.User.IsInRole("SuperAdmin");
            model.CanUserDelete = this.User.IsInRole("Admin") || this.User.IsInRole("SuperAdmin");
            // viewModel.Orders = (await this.orderService.GetOrdersByPartnerAsync((await this.partnerService.FindByIdAsync(id)))).OrderBy(x=>x.ModifiedOn).ToList();

            return View(model);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            PartnerViewModel model = this.partnerMapper.MapFrom(await this.partnerService.GetByIdAsync(id));
            model.Cities = new SelectList(await this.townService.GetAllTownsAsync(), "Id", "Name")
                         .OrderBy(x => x.Text);
            model.AddressesList = await this.addressService.GetAllAddressesAsync();

            cache.Set(userManager.GetUserName(User), model.Name);

            return View(model);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(PartnerViewModel model)
        {
            ModelState.Remove("Id");
            ModelState.Remove("Address");
            ModelState.Remove("City");
            var originPartnerName = this.cache.Get(userManager.GetUserName(User)).ToString();

            if ((await this.partnerService.GetAllPartners()).Any(p => p.Name == model.Name) && originPartnerName!=model.Name)
            {
                ModelState.AddModelError("Name", "Name is already used");
            }

            if (model.AddressId == 0 && model.City == null ||
                model.AddressId == 0 && model.City == "Please choose a city")
            {
                ModelState.AddModelError("City", "City is required");
            }
            if (model.AddressId == 0 && model.Address == null)
            {
                ModelState.AddModelError("Address", "Address is required");
            }
            if (model.AddressId == 0)
            {
                ModelState.Remove("AddressId");
            }
            model.Cities = new SelectList(await this.townService.GetAllTownsAsync(), "Id", "Name").OrderBy(x => x.Text);
            model.AddressesList = await this.addressService.GetAllAddressesAsync();

            if (ModelState.IsValid)
            {
                Town town;
                Address address;
                if (model.AddressId == 0)
                {
                    town = await this.townService.GetTownAsync(model.City);

                    if (town == null || town.IsDeleted)
                    {
                        town = await this.townService.AddAsync(model.City);
                    }

                    address = await this.addressService.AddAsync(town, model.Address);
                }
                else
                {
                    address = await this.addressService.GetAddressByIdAsync(model.AddressId);
                }

                var updatedPartner = await this.partnerService.GetByIdAsync(model.Id);
                updatedPartner.Address = address;
                updatedPartner.ModifiedOn = DateTime.Now;
                updatedPartner.Name = model.Name;
                updatedPartner.VAT = model.VAT;

                await this.partnerService.UpdateAsync(updatedPartner);

                cache.Remove(userManager.GetUserName(User));
                return RedirectToAction(nameof(Details), new { id = updatedPartner.Id });
            }
            else
            {
                return View(model);
            }
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            Partner partnerToDelete = await this.partnerService.DeleteAsync(id);
            PartnerViewModel model = this.partnerMapper.MapFrom(partnerToDelete);

            return View(model);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> SearchPartnerById([FromQuery]PartnerViewModel model)
        {
            model.CanUserEdit = model.CreatorId == this.User.GetId() || this.User.IsInRole("Admin") || this.User.IsInRole("SuperAdmin");
            model.CanUserDelete = this.User.IsInRole("Admin") || this.User.IsInRole("SuperAdmin");
            if (model.Id == 0)
            {
                return View();
            }
            try
            {
                model.SearchResult = this.partnerMapper.MapFrom(await this.partnerService.GetByIdAsync(model.Id));
            }
            catch (ArgumentException)
            {
                return View(model);
            }

            return View(model);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> SearchPartnerByName([FromQuery]PartnerViewModel model)
        {
            model.CanUserEdit = model.CreatorId == this.User.GetId() || this.User.IsInRole("Admin") || this.User.IsInRole("SuperAdmin");

WHMSWebApp2/Views/Partner/Create.cshtml
@model PartnerViewModel
@{
    ViewData["Title"] = "Create";
}

<h2>Add New Partner</h2>

<div asp-validation-summary="All">
    <span>@*Please correct the following errors*@</span>
</div>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" placeholder="Enter Partner Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AddressId" placeholder="Enter New Address" class="control-label">Address</label><br />

                <select asp-for="AddressId" placeholder="Enter New Address" class="form-control">
                    <option>Choose from existing addresses</option>
                    @foreach (var address in Model.AddressesList)
                    {
                        <option value="@address.Id">@address.Town.Name, @address.Text </option>
                    }

                </select>

                <span asp-validation-for="AddressId" class="text-danger"></span>
            </div>
            <hr />
            <p>
                <a class="btn btn-primary" data-toggle="collapse" href="#multiCollapseExample1" role="button" aria-expanded="false" aria-controls="multiCollapseExample1">Add New Address</a>

            </p>
            <div class="collapse multi-collapse" id="multiCollapseExample1">
                <div class="card card-body">

                    <input asp-for="City" placeholder="Enter new city name" class="form-control" />

                    <div class="form-group">
                        <label asp-for="City" class="control-label">or</label>
                        <select asp-for="City" class="form-control" asp-items="Model.Cities">
                            <option>Choose from existing cities</option>
                        </select>

                        <input asp-for="Address" placeholder="Enter New Address" class="form-control" />
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <hr />

            <div class="form-group">
                <label asp-for="VAT" class="control-label"></label>
                <input asp-for="VAT" placeholder="Enter VAT Number, e.g.BG123456789" class="form-control" />
                <span asp-validation-for="VAT" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a class="btn btn-secondary" href='javascript:history.go(-1)'>Go Back</a>

                <input type="submit" value="Create Partner" class="btn btn-success" />
            </div>

        </form>
    </div>
</div>

WHMSWebApp2/Views/Partner/Delete.cshtml
@model PartnerViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1> Partner wint name: @Model.Name is deleted!</h1>

WHMSWebApp2/Views/Partner/Details.cshtml
@model PartnerViewModel

@{
    ViewData["Title"] = "Details";
    ViewBag.Title = Model.Name;
}

<div>
    <h2>Partner: @Model.Name Details</h2>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.VAT)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.VAT)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Creator)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Creator)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedOn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ModifiedOn)
        </dd>
    </dl>
    
</div>
<div>
    <a class="btn btn-secondary" href='javascript:history.go(-1)'>Go Back</a>

    @if (Model.CanUserEdit)
    {
        <a class="btn btn-info" style="width:70.59px" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>

    }
    @if (Model.CanUserDelete)
    {
        <!-- Button to Open the Modal -->
        <button type="button" class="btn btn-danger" style="width:70.59px" data-toggle="modal" data-target="#myModal">
            Delete
        </button>

        <!-- The Modal -->
        <div class="modal fade" id="myModal">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">

                    <!-- Modal Header -->
                    <div class="modal-header">
                        <h4 class="modal-title">Confirmation</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>

                    <!-- Modal body -->
                    <div class="modal-body">
                        Are you sure you want to delete this partner?
                    </div>

                    <!-- Modal footer -->
                    <div class="modal-footer">
                        <button type="button" class="btn btn-success" data-dismiss="modal">Cancel</button>
                        <form asp-controller="Partner" asp-action="Delete" asp-route-id="@Model.Id" method="post">
                            <button class="btn btn-danger" type="submit">Delete</button>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    }

</div>

WHMSWebApp2/Views/Partner/Edit.cshtml
@model PartnerViewModel
@{
    ViewData["Title"] = "Edit";
}

<h2>Edit Partner</h2>

<div asp-validation-summary="All">
</div>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" placeholder="Enter Partner Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AddressId" placeholder="Enter New Address" class="control-label">Address</label><br />

                <select asp-for="AddressId" placeholder="Enter New Address" class="form-control">
                    <option>Choose from existing addresses</option>
                    @foreach (var address in Model.AddressesList)
                    {
                        <option value="@address.Id">@address.Town.Name, @address.Text </option>
                    }

                </select>
            </div>
            <hr />
            <p>
                <a class="btn btn-primary" data-toggle="collapse" href="#multiCollapseExample1" role="button" aria-expanded="false" aria-controls="multiCollapseExample1">Add New Address</a>

            </p>
            <div class="collapse multi-collapse" id="multiCollapseExample1">
                <div class="card card-body">

                    <input asp-for="City" placeholder="Enter new city name" class="form-control" />

                    <div class="form-group">
                        <label asp-for="City" class="control-label">or</label>
                        <select asp-for="City" class="form-control" asp-items="Model.Cities">
                            <option>Choose from existing cities</option>
                        </select>

                        <input asp-for="Address" placeholder="Enter New Address" class="form-control" />
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <hr />

            <div class="form-group">
                <label asp-for="VAT" class="control-label"></label>
                <input asp-for="VAT" placeholder="Enter VAT Number, e.g.BG123456789" class="form-control" />
                <span asp-validation-for="VAT" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a class="btn btn-secondary" href='javascript:history.go(-1)'>Go Back</a>

                <input type="submit" value="Save changes" class="btn btn-success" />
            </div>

        </form>
    </div>
</div>

WHMSWebApp2/Views/Partner/NoPartnerFound.cshtml
@{
    ViewData["Title"] = "NoPartnerFound";
}

@*<partial name="_SearchPartner" />*@


<h2>No partner has been found!</h2>

<a href='javascript:history.go(-1)'>Go Back to Previous Page</a>

WHMSWebApp2/Views/Partner/Search.cshtml
@{
    ViewData["Title"] = "Partner";
}

<partial name="_Search" />

<partial name="_SearchPartner" />

WHMSWebApp2/Views/Partner/SearchPartnerById.cshtml
@model PartnerViewModel
@{
    ViewData["Title"] = "SearchPartnerById";
}

<h3>Search for Partner by ID</h3>

<div class="row mt-5">
    <form class="col-lg-6" asp-controller="Partner" asp-action="SearchPartnerById" method="get">
        <div class="row">
            <div class="col-sm-9">
                <input asp-for="@Model.Id" placeholder="Search..." class="form-control" />
                <span asp-validation-for="@Model.Id" class="text-danger"></span>
            </div>
            <div class="col-sm-3">
                <button type="submit" class="btn btn-success">Search!</button>
            </div>
        </div>
    </form>
</div>

<div class="row mt-5">
    <div class="col-lg-6">
        @if (Model != null)
        {

            if (Model.Id == 0 || Model.SearchResult == null)
            {
                <p class="alert alert-info">There is no partner with ID: @Model.Id</p>
            }
            else
            {
                <partial name="_PartnerPartial" model="Model.SearchResult" />
            }
        }
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

WHMSWebApp2/Views/Partner/SearchPartnerByName.cshtml
@model PartnerViewModel
@{
    ViewData["Title"] = "SearchPartnerByName";
}

<h3>Search for Partner by Name</h3>

<div class="row mt-5">
    <form class="col-lg-6" asp-controller="Partner" asp-action="SearchPartnerByName" method="get">
        <div class="row">
            <div class="col-sm-9">
                <input asp-for="@Model.Name" placeholder="Search..." class="form-control" />
                <span asp-validation-for="@Model.Name" class="text-danger"></span>
            </div>
            <div class="col-sm-3">
                <button type="submit" class="btn btn-success">Search!</button>
            </div>
        </div>
    </form>
</div>

<div class="row mt-5">
    <div class="col-lg-6">
        @if (Model != null)
        {

            if (string.IsNullOrWhiteSpace(Model.Name) || Model.SearchResult==null)
            {
                <p class="alert alert-info">There is no partner with name: @Model.Name</p>
            }
            else
            {
                <partial name="_PartnerPartial" model="Model.SearchResult" />
            }
        }
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

WHMSWebApp2/Views/Partner/SearchPartnerByVAT.cshtml
@model PartnerViewModel
@{
    ViewData["Title"] = "SearchPartnerByVAT";
}

<h3>Search for Partner by VAT</h3>

<div class="row mt-5">
    <form class="col-lg-6" asp-controller="Partner" asp-action="SearchPartnerByVAT" method="get">
        <div class="row">
            <div class="col-sm-9">
                <input asp-for="@Model.VAT" placeholder="Search..." class="form-control" />
                <span asp-validation-for="@Model.VAT" class="text-danger"></span>
            </div>
            <div class="col-sm-3">
                <button type="submit" class="btn btn-success">Search!</button>
            </div>
        </div>
    </form>
</div>

<div class="row mt-5">
    <div class="col-lg-6">
        @if (Model != null)
        {

            if (string.IsNullOrWhiteSpace(Model.VAT) || Model.SearchResult == null)
            {
                <p class="alert alert-info">There is no partner with VAT: @Model.VAT</p>
            }
            else
            {
                <partial name="_PartnerPartial" model="Model.SearchResult" />
            }
        }
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

WHMSWebApp2/Views/Partner/_AddNewAddress.cshtml
@model PartnerViewModel

<text>Or</text>
<div class="dropdown-divider">

    <label asp-for="City" class="control-label">Enter City</label><br />
    <input list="AddressesList" name="Address" />
    <datalist id="browsers">
        <select asp-for="City">
            <option asp-for="AddressId" class="form-control" />
            @foreach (var city in Model.Cities)
            {
                <option value="City">@city.Text </option>
            }

        </select>

    </datalist>
</div>
<div class="form-group">
    <label asp-for="Address" class="control-label"></label>
    <input asp-for="Address" class="form-control" />
    <span asp-validation-for="Address" class="text-danger"></span>

</div>